### ISSUE TITLE
General configuration issues

### ISSUE THREAD

**Issue by emphasize** [JarbasHiveMind/skill-hivemind#4]
- changes made in mycrofts backend have no effect to the configuration file ~/jarbasHiveMind/HiveMind.conf (but somehow he kicked out my manually set "sectret" entry)
- the wocksocket port seems to be hardcoded to port "6789"  (seleneUI:8020, conf: 5678, port:6789) 😛 

(unless there is another conf somewhere)

Figuring that out the connection is established 👍 (with ssl enabled i dont think there is a possibility to connect)

**Comment by emphasize** [comment]
Maybe this is known but i don't get the HiveMind "listen to" port option in the backend. When i set it to "6789" i'm running into exceptions saying "port in use". Just want to report that those are interfering.

**Comment by JarbasAl** [comment]
logs please, i guess it isnt restarting properly after receiving backend change, does restarting mycroft solve it?

regarding ssl, self signed certificates (auto generated by hivemind) are usually blocked, browsers and node red wont accept them. You can set a .crt file in the .conf

**Comment by emphasize** [comment]
I couldn't reproduce the error, but after after setting the backend option to 6789 jarbas_hive_mind shouldn't listen to 5678. Maybe he mixed up something in this process.

```
15:49:28.459 - jarbas_hive_mind_red:start_announcing:44 - INFO - Registering zeroconf:HiveMind-NodeRed-websocket ws://192.168.188.38:6789
15:49:28.478 - jarbas_hive_mind:unsafe_listen:213 - INFO - HiveMind Listening (UNSECURED): ws://0.0.0.0:6789
...
15:49:31.208 - jarbas_hive_mind.discovery.ssdp:register:108 - INFO - Registering upnp:HiveMind-websocket (http://192.168.188.38:8088/device.xml)
15:49:31.302 - jarbas_hive_mind:unsafe_listen:213 - INFO - HiveMind Listening (UNSECURED): ws://0.0.0.0:5678
15:49:31.560 - jarbas_hive_mind.master:onConnect:44 - INFO - Client connecting: tcp4:192.168.188.2:53646
15:49:31.582 - jarbas_hive_mind.master:register_client:240 - INFO - registering client: tcp4:192.168.188.2:53646
15:49:31.585 - jarbas_hive_mind.master:onOpen:87 - INFO - WebSocket connection open.

```

**Comment by JarbasAl** [comment]
6789 is the NodeRed skill, thats the websocket to connect your flows to

**Comment by emphasize** [comment]
Indeed confusing: 
5678 should't be listened to, since this is not what i set in the backend.
Checked the ~/jarbasHiveMind/HiveMind.conf and 5678 is set in the conf, which it shouldn't.
Lately another configuration file was created under .config/mycroft/skills/skill-hivemind.jarbasskills stating 5678
(checked the place yesterday - nothing there)

Maybe associated with this config problem:
When utterances are sent through the master to node-red these are sent, but an exception is thrown
```
 16:30:57.497 | ERROR    |  1873 | concurrent.futures | exception calling callback for <Future at 0x72281c30 state=finished raised TypeError>
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_executor.py", line 60, in _callback
    self.emit('error', exc)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 111, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 83, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/jarbas_hive_mind/master/__init__.py", line 415, in handle_outgoing_mycroft
    if peer and peer in self.clients:
TypeError: unhashable type: 'list'
```

**Comment by JarbasAl** [comment]
this has been fixed https://github.com/JarbasHiveMind/HiveMind-core/issues/19

sorry it took so long

**Comment by JarbasAl** [comment]
this issue includes more things, reopening, error in last comment is what was fixed @emphasize
